### ISSUE TITLE
Please set $OCIO first message

### ISSUE THREAD

**Issue by EistenGaming** [eglaubauf/egMatLib#4]
I tried to save a principled (mantra) shader to the library and got the message "Please set $OCIO first".  Any reference to relevant documentation available?

Cheers,
Zen

**Comment by eglaubauf** [comment]
Hey, this means you need to set an environment variable for OCIO/ACES first.

Here's the Houdini documentation for setting Environment Variables:
https://www.sidefx.com/docs/houdini/basics/config_env.html 

A precompiled OCIO/ACES config can be found here:
https://github.com/colour-science/OpenColorIO-Configs/tree/feature/aces-1.2-config/aces_1.2

On windows your Houdini.env could look like this:
OCIO="C:\Users\foobar\aces_1.2\config.ocio"

Colormanagement and ACES is a bigger topic by itself to be considered.
